### ISSUE TITLE
Plugin does not appear to be publishing

### ISSUE THREAD

**Issue by twotwisted** [meri-imperiumi/signalk-aws-iot#21]
Hey

I have installed SignalK and the AWS plugin, placed certificates and can connect to IOT AWS, but no data is being sent.

Turning debug on in Signalk shows no logs AWS plugin is trying to send or do anything.

![AWS Plugin](https://user-images.githubusercontent.com/29116227/98079512-06b8d100-1ec8-11eb-9cb3-944e75b8abeb.png)

Node v14.15.0
NPM 6.14.8
aws-iot-device-sdk@2.2.6

Ive tested using node examples with same certs and ID and it works.

**Comment by bergie** [comment]
Did you set which states the plugin should send data in? If you're not using the autostate plugin (or something else that sets `navigation.state`), you should enable sending data in `default` state.

See #3

Please reopen this issue if that doesn't solve it for you.

**Comment by twotwisted** [comment]
By default "default" and "motoring" are set and checking the data browser indicates "motoring" is set.

![image](https://user-images.githubusercontent.com/29116227/98176532-d8c9a000-1f4c-11eb-9233-f59f110f8144.png)
![AWS Plugin 1](https://user-images.githubusercontent.com/29116227/98176564-e54df880-1f4c-11eb-8353-2e139a33a3f0.png)

Policy below is fairly open, but I am new to AWS

````{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:xxx:topic/sdk/test/java",
        "arn:aws:iot:us-west-2:xxx:topic/sdk/test/Python",
        "arn:aws:iot:us-west-2:xxx:topic/topic_1",
        "arn:aws:iot:us-west-2:xxx:topic/topic_2",
        "arn:aws:iot:us-west-2:xxx:topic/sdk-nodejs-*",
        "arn:aws:iot:us-west-2:xxx:topic/Khaleesi/*",
        "arn:aws:iot:us-west-2:xxx:topic/signalk",
        "arn:aws:iot:us-west-2:xxx:topic/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:xxx:topicfilter/sdk/test/java",
        "arn:aws:iot:us-west-2:xxx:topicfilter/sdk/test/Python",
        "arn:aws:iot:us-west-2:xxx:topicfilter/topic_1",
        "arn:aws:iot:us-west-2:xxx:topicfilter/topic_2",
        "arn:aws:iot:us-west-2:xxx:topicfilter/sdk-nodejs-*",
        "arn:aws:iot:us-west-2:xxx:topicfilter/Khaleesi/*",
        "arn:aws:iot:us-west-2:xxx:topicfilter/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:xxx:client/sdk-java",
        "arn:aws:iot:us-west-2:xxx:client/basicPubSub",
        "arn:aws:iot:us-west-2:xxx:client/sdk-nodejs-*",
        "arn:aws:iot:us-west-2:xxx:client/Khaleesi*"
      ]
    }
  ]
}
````

**Comment by bergie** [comment]
What does the plug-in say about its status in the Signal K front page?

**Comment by twotwisted** [comment]
"Connected to AWS IoT Core"

I have tried the plugging to update navigation state and when not set to a state configured in AWS Plugin I get Connected, but not sending due to state zzz.

I have also tried down grading to node 10, which apparently is the only supported version, uninstall and reinstall AWS plugin, but still not luck. I have also followed assistance on Signalk Google Groups to completely open Policy in AWS, but same result.

**Comment by bergie** [comment]
Can you try downgrading to the version 1.0.0 of this plug-in? That would help to eliminate some options

**Comment by twotwisted** [comment]
Already tested, so I have manually installed version 1.0.0 and then copied it to ~home/.signalk/node_modules/ I can now see data in the debug window and can subscribe to it on AWS. I then upgraded through Signalk and get same issue. I also installed new version same way manually, but same issue.

So it is looking like the new version has a bug.

**Comment by bergie** [comment]
Thanks! Then I'll have to take a deeper look.

**Comment by bergie** [comment]
@twotwisted #27 should fix it. I'll release it today
